In [1]:
import os
print(os.getcwd())
os.chdir('d:\\vscode_machineLearning\\internship\\Customer-Churn-Prediction')
print(os.getcwd())

d:\vscode_machineLearning\internship\Customer-Churn-Prediction\experiments\model_training
d:\vscode_machineLearning\internship\Customer-Churn-Prediction

In [2]:
import pandas as pd

In [3]:
train_df = pd.read_csv(r'artifacts/transformed_data/train_transformed.csv')
test_df = pd.read_csv(r'artifacts/transformed_data/test_transformed.csv')

In [4]:
train_df

,Houston,LosAngeles,Miami,NewYork,Age,Subscription_Length_Months,Monthly_Bill,Total_Usage_GB,Gender,Churn
0,0.0,0.0,0.0,0.0,0.980769,0.217391,0.985429,0.024444,1.0,1.0
1,0.0,1.0,0.0,0.0,0.480769,1.000000,0.999286,0.342222,0.0,1.0
2,0.0,0.0,1.0,0.0,0.653846,0.260870,0.041429,0.117778,0.0,0.0
3,0.0,0.0,1.0,0.0,0.423077,0.130435,0.979857,0.535556,0.0,0.0
4,0.0,0.0,1.0,0.0,0.153846,0.043478,0.505143,0.291111,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
79995,0.0,0.0,1.0,0.0,0.692308,0.956522,0.346714,0.902222,1.0,0.0
79996,0.0,1.0,0.0,0.0,0.403846,0.739130,0.383143,0.844444,1.0,0.0
79997,0.0,1.0,0.0,0.0,0.500000,0.956522,0.347000,0.115556,1.0,1.0
79998,0.0,0.0,1.0,0.0,0.826923,0.913043,0.316143,0.160000,0.0,0.0
79999,0.0,0.0,1.0,0.0,0.750000,0.913043,0.347571,0.437778,1.0,1.0

In [5]:
train_df.describe()

,Houston,LosAngeles,Miami,NewYork,Age,Subscription_Length_Months,Monthly_Bill,Total_Usage_GB,Gender,Churn
count,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000
mean,0.201462,0.200325,0.199075,0.198412,0.500679,0.499773,0.501100,0.499662,0.501188,0.498638
std,0.401095,0.400246,0.399307,0.398807,0.293671,0.300885,0.289151,0.289606,0.500002,0.500001
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.250000,0.217391,0.250964,0.248889,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.500000,0.478261,0.500714,0.500000,1.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.750000,0.782609,0.752571,0.751111,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

#### dependent and independent features

In [12]:
X_train = train_df.drop('Churn',axis=1)
y_train = train_df['Churn']
X_test = test_df.drop('Churn',axis=1)
y_test = test_df['Churn']

In [13]:
X_train

,Houston,LosAngeles,Miami,NewYork,Age,Subscription_Length_Months,Monthly_Bill,Total_Usage_GB,Gender
0,0.0,0.0,0.0,0.0,0.980769,0.217391,0.985429,0.024444,1.0
1,0.0,1.0,0.0,0.0,0.480769,1.000000,0.999286,0.342222,0.0
2,0.0,0.0,1.0,0.0,0.653846,0.260870,0.041429,0.117778,0.0
3,0.0,0.0,1.0,0.0,0.423077,0.130435,0.979857,0.535556,0.0
4,0.0,0.0,1.0,0.0,0.153846,0.043478,0.505143,0.291111,1.0
...,...,...,...,...,...,...,...,...,...
79995,0.0,0.0,1.0,0.0,0.692308,0.956522,0.346714,0.902222,1.0
79996,0.0,1.0,0.0,0.0,0.403846,0.739130,0.383143,0.844444,1.0
79997,0.0,1.0,0.0,0.0,0.500000,0.956522,0.347000,0.115556,1.0
79998,0.0,0.0,1.0,0.0,0.826923,0.913043,0.316143,0.160000,0.0
79999,0.0,0.0,1.0,0.0,0.750000,0.913043,0.347571,0.437778,1.0

In [14]:
y_train

0        1.0
1        1.0
2        0.0
3        0.0
4        0.0
        ...
79995    0.0
79996    0.0
79997    1.0
79998    0.0
79999    1.0
Name: Churn, Length: 80000, dtype: float64

In [15]:
X_test

,Houston,LosAngeles,Miami,NewYork,Age,Subscription_Length_Months,Monthly_Bill,Total_Usage_GB,Gender
0,0.0,0.0,1.0,0.0,0.596154,0.130435,0.777651,0.840000,1.0
1,0.0,0.0,0.0,0.0,0.038462,0.695652,0.260074,0.802222,1.0
2,0.0,0.0,0.0,1.0,0.807692,0.130435,0.037868,0.875556,1.0
3,0.0,0.0,0.0,1.0,0.288462,0.826087,0.542298,0.917778,1.0
4,1.0,0.0,0.0,0.0,0.653846,0.260870,0.619606,0.004444,0.0
...,...,...,...,...,...,...,...,...,...
19995,0.0,1.0,0.0,0.0,0.653846,0.695652,0.290083,0.968889,0.0
19996,0.0,0.0,0.0,0.0,0.557692,0.782609,0.893541,0.411111,0.0
19997,0.0,0.0,0.0,1.0,0.750000,0.086957,0.778794,0.491111,1.0
19998,0.0,0.0,0.0,1.0,0.096154,0.173913,0.295084,0.557778,1.0
19999,0.0,0.0,0.0,0.0,0.230769,0.695652,0.741069,0.497778,0.0

In [16]:
y_test

0        1.0
1        0.0
2        1.0
3        1.0
4        0.0
        ...
19995    1.0
19996    1.0
19997    1.0
19998    1.0
19999    0.0
Name: Churn, Length: 20000, dtype: float64

## training

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [19]:
rfc = RandomForestClassifier(n_estimators=132,oob_score=True)
rfc

RandomForestClassifier(n_estimators=132, oob_score=True)

In [20]:
rfc.fit(X_train,y_train)

RandomForestClassifier(n_estimators=132, oob_score=True)

In [30]:
y_pred = rfc.predict(X_test)

In [31]:
from sklearn.metrics import confusion_matrix, recall_score, accuracy_score, precision_score, classification_report

def evaluate(true, pred):
    cm = confusion_matrix(true, pred)
    accuracy = accuracy_score(true, pred)
    recall = recall_score(true, pred)
    
    precision = precision_score(true, pred)
    
    report = classification_report(true, pred)
    
    return {
        'confusion_matrix': cm,
        'accuracy': accuracy,
        'recall': recall,
        'precision': precision,
        'classification_report': report
    }

In [32]:
results = evaluate(y_test,y_pred)

In [33]:
# print("Confusion Matrix:")
print(results['confusion_matrix'])
print("Accuracy:", results['accuracy'])
print("Recall:", results['recall'])
print("Precision:", results['precision'])
print("Classification Report:")
print(results['classification_report'])

Confusion Matrix:
[[5239 4873]
 [5184 4704]]
Accuracy: 0.49715
Recall: 0.47572815533980584
Precision: 0.4911767776965647
Classification Report:
              precision    recall  f1-score   support

         0.0       0.50      0.52      0.51     10112
         1.0       0.49      0.48      0.48      9888

    accuracy                           0.50     20000
   macro avg       0.50      0.50      0.50     20000
weighted avg       0.50      0.50      0.50     20000